;; Generated by allisp markdown->lisp. Do not edit manually.
;; markdown source: /Users/alpaca/allisp/./skills/allisp/SKILL.md
;; generated: 2026-07-18T16:34:52

(defmacro generated-by (generator &key source form generated-at)
  `(progn
     (def *generated-by*
       (quote (:generator ,generator
               :source ,source
               :form ,form
               :generated-at ,generated-at)))
     *generated-by*))

(generated-by markdown->lisp :source "<one-liner>" :form
 (markdown->lisp runbook-markdown :from "./skills/allisp/SKILL.md" :out
  "skill.lisp")
 :generated-at "2026-07-18T16:34:52")

(skill :name allisp :aliases (思考lisp処理系) :triggers
 ((run-file .lisp) (run-form s-expression) pseudo-run evaluate dry-run refresh
  summarize-result)
 :usage (/allisp file (&optional --dry-run --refresh --strict (--model opus))))

(section 0 binary-resolution
 (resolve-executable :name allisp :probe (command -v allisp) :fallback
  (repository-path "bin/allisp") :otherwise
  (require-installation :command (make install))))

(section 1 argument-translation
 (direct-arguments :source (/allisp :rest arguments) :target
  (allisp run :splice arguments))
 (translation-table ((request-any "実行して" "評価して" "擬似実行して") (allisp run file))
  ((request-any "どこが LLM 行きか" "コスト見積り" "予告") (allisp run file --dry-run))
  ((request-any "考え直して" "再思考" "キャッシュ無視で") (allisp run file --refresh))
  ((request-any "厳格に" "エラーで止めて") (allisp run file --strict))
  ((request-any "opus で" "もっと深く考えさせて") (allisp run file --model opus))
  ((request-any "リポジトリを読ませずに" "探索なしで") (allisp run file --no-explore))
  ((request-any "結果を〜に保存して" "出力先を変えて") (allisp run file --out-dir directory))
  ((request "この S 式を直接評価") (allisp --one-liner form))
  ((request-any "前と結果を比べて" "前提を変えたら何が変わった?")
   (allisp diff old-result new-result))
  ((request specific-expression-refresh) (propose (llm expression :fresh t)))
  ((request-any "曖昧でもいいから動くところまで" "仮定を補って実行して")
   (propose (fix expression) :assumptions-binding :code)))
 (when (ambiguous file)
  (let
   ((candidates
     (find-files :root current-workspace :extension ".lisp" :exclude
      ("output/" ".allisp/"))))
   (confirm-with-user candidates)))
 (constraint flags :composable t)
 (example (allisp run file --refresh --model opus)))

(section 2 execution-procedure
 (step 1 (require-first (allisp run file :splice requested-flags --dry-run))
  (let ((oracle-count (uncached-oracle-count dry-run-result)))
   (when (> oracle-count 10)
    (report-before-execution :oracle-count oracle-count :estimated-seconds
     (range (* oracle-count 10) (* oracle-count 45)) :subscription-consumption
     t)
    (await-user-confirmation))))
 (step 2 (run-in-background (allisp run file :splice requested-flags))
  (track-progress :pattern
   ("[allisp]" oracle "#" oracle-number (choice miss hit))))
 (step 3
  (constraint --refresh :effect discard-all-cache-and-regenerate :allowed-when
   (user-explicitly-requests rethink refresh ignore-cache))))

(section 3 result-reading-and-reporting
 (exit-codes (0 success) (1 partial-evaluation-with-error-values)
  (2 invalid-arguments) (3 internal-error))
 (output-layout :directory (path (input-file-directory file) "output/")
  :result-file (path output-directory (concat (file-stem file) ".result.lisp"))
  :trace-file (path output-directory (concat (file-stem file) ".trace.lisp")))
 (result-schema
  (result :v 2 :n form-index :form original-form :value evaluated-value))
 (trace-schema :fields
  (hash model cache-status generated-code execution-status value) :cache-status
  (hit miss) :execution-status (executed intermediate))
 (report-procedure (read result-file)
  (summarize :statistics
   (form-count oracle-miss-count oracle-hit-count error-count) :oracle-values
   (select oracle-returned-values :prioritize (conclusion finding root-cause))
   :omit (deterministic-binding-results closure) :errors
   (all (error :type error-type :form error-form :detail error-detail))
   :remediation
   ((:oracle-failure (rerun :retry-only failed-oracle-forms))
    (:unbound-in-pure (inspect-undefined-form-inside pure))
    (:use-not-found (correct-path-of @use))))))

(section 4 semantics-summary
 (semantic deterministic-replay :condition rerun :mechanism oracle-cache
  :performance (when (= oracle-miss-count 0) (< elapsed-seconds 1))
  :invalidation edited-expressions-only)
 (semantic repository-exploration :scope file-execution-oracles :tools
  (Read Glob Grep) :access read-only :order
  (explore-repository generate-lisp-code))
 (semantic cache-stability :condition surrounding-files-changed
  :cached-result-change nil :refresh-command --refresh)
 (semantic oracle-cache :location (path project-root ".allisp/oracle/"))
 (semantic @use :syntax (@use relative-path) :inherits definitions
  :accepted-input (source-lisp output-result-lisp) :chain
  ((upstream (def name value))
   (downstream (@use upstream-result) (restore name :llm-calls 0)))
  :latest-value-binding last-result)
 (semantic generate-file :syntax (generate-file path :rest body) :value-written
  final-evaluation-value :provenance-marker generated-by :dry-run-write nil
  :non-lisp-output
  (constraint (not (extension= path ".lisp")) (stringp final-evaluation-value)
   :encoding raw-text)
  :examples (Python markdown))
 (semantic --one-liner :output last-evaluation-value :destination
  standard-output :generate-result-file nil :generate-trace-file nil)
 (references (language-specification "docs/language.md")
  (design-decisions "DESIGN.md")))
