name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  SBCL_VERSION: "2.5.10"
  QUICKLISP_DIST_VERSION: "2025-06-22"

permissions:
  contents: write

jobs:
  build-unix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            asset_name: macos-arm64
          - os: ubuntu-latest
            asset_name: linux-x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Roswell / Quicklisp
        uses: actions/cache@v4
        with:
          path: |
            ~/.roswell
            ~/.cache/common-lisp
          key: ${{ runner.os }}-${{ matrix.asset_name }}-roswell-${{ env.SBCL_VERSION }}-${{ env.QUICKLISP_DIST_VERSION }}-${{ hashFiles('allisp.asd') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.asset_name }}-roswell-${{ env.SBCL_VERSION }}-${{ env.QUICKLISP_DIST_VERSION }}-

      - name: Install Roswell
        run: curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh

      - name: Install pinned SBCL
        run: |
          ros install sbcl-bin/${{ env.SBCL_VERSION }}
          ros use sbcl-bin/${{ env.SBCL_VERSION }}

      - name: Pin Quicklisp dist
        run: |
          ros run --eval '(ql-dist:install-dist "http://beta.quicklisp.org/dist/quicklisp/${{ env.QUICKLISP_DIST_VERSION }}/distinfo.txt" :prompt nil)' \
                  --eval '(quit)'

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: Package
        run: |
          stage=allisp-${{ github.ref_name }}-${{ matrix.asset_name }}
          mkdir "$stage"
          cp dist/allisp "$stage/allisp"
          cp LICENSE README.md "$stage/"
          tar czf "$stage.tar.gz" "$stage"

      - uses: actions/upload-artifact@v4
        with:
          name: allisp-${{ matrix.asset_name }}
          path: allisp-${{ github.ref_name }}-${{ matrix.asset_name }}.tar.gz
          if-no-files-found: error

  release:
    needs: [build-unix]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          generate_release_notes: true
